version: "3.9"
services:
  db:
    image: mysql:5.7
    # map a volume to a path inside container
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
  opencart:
    build: .
    volumes:
      - ./upload:/var/www/html
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
  # list volumes to be created by docker
volumes:
  db_data:
    driver: local